//all available language data of gnews api
export const languages = [
  { name: "English", value: "en" },
  { name: "Hindi", value: "hi" },
  { name: "Malayalam", value: "ml" },
  { name: "Arabic", value: "ar" },
  { name: "German", value: "de" },
  { name: "Greek", value: "el" },
  { name: "Spanish", value: "es" },
  { name: "French", value: "fr" },
  { name: "Hebrew", value: "he" },
  { name: "Italian", value: "it" },
  { name: "Japanese", value: "ja" },
  { name: "Marathi", value: "mr" },
  { name: "Dutch", value: "nl" },
  { name: "Norwegian", value: "no" },
  { name: "Portuguese", value: "pt" },
  { name: "Romanian", value: "ro" },
  { name: "Russian", value: "ru" },
  { name: "Swedish", value: "sv" },
  { name: "Tamil", value: "ta" },
  { name: "Telugu", value: "te" },
  { name: "Ukrainian", value: "uk" },
  { name: "Chinese", value: "zh" },
];
